# SPDX-License-Identifier: Apache-2.0
name: graphcap
services:
  gcap_server:
    container_name: gcap_server
    build:
      context: ../
      dockerfile: server/Dockerfile.server
    ports:
      - 32100:32100
    volumes:
      - ../lib/graphcap:/app/lib/graphcap
      - ../server:/app/server
      - ../config:/workspace/config
      - ../.local:/workspace/.local
      - ../datasets:/workspace/datasets
    environment:
      - HOST_PLATFORM=${HOST_PLATFORM:-linux}
      - PYTHONPATH=/app/server
      - DATABASE_URL=postgresql+asyncpg://graphcap:graphcap@gcap_postgres:5432/graphcap
    env_file:
      - ../.env
    develop:
      watch:
        - action: sync+restart
          path: ../lib/graphcap
          target: /app/lib/graphcap
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: sync
          path: ../server/server
          target: /app/server/server
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
    networks:
      - graphcap
    depends_on:
      gcap_postgres:
        condition: service_healthy

  gcap_postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: graphcap
      POSTGRES_PASSWORD: graphcap
      POSTGRES_DB: graphcap
    ports:
      - "35432:5432"
    volumes:
      - graphcap_server_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graphcap"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - graphcap

  gcap_ui:
    container_name: gcap_ui
    build:
      context: ../ui
      dockerfile: Dockerfile.client
      args:
        - VITE_API_URL=http://localhost:32200/api
    ports:
      - "32200:32200"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:32200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

    develop:
      watch:
        - action: sync
          path: ../ui/src
          target: /app/src
          ignore:
            - "**/.git"
            - "**/node_modules"
            - "**/.DS_Store"
        - action: sync
          path: ../ui/public
          target: /app/public
        - action: sync
          path: ../ui/index.html
          target: /app/index.html
        - action: sync
          path: ../ui/vite.config.ts
          target: /app/vite.config.ts
        - action: sync+restart
          path: ../ui/package-lock.json
          target: /app/package-lock.json
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=http://localhost:32100/api

    networks:
      - graphcap

volumes:
  graphcap_server_db:

networks:
  graphcap:
    driver: bridge
